settings:
  lib_name: sky130_dff
  temperature: 25
  multithreaded: False
  units:
    voltage: V
    time: ns
    capacitive_load: pF
    energy: pJ
  named_nodes:
    primary_power:
      name: VDD
      voltage: 1.8
    primary_ground:
      name: VSS
      voltage: 0.0

cells:
  dff:
    netlist: cells/dff.spice
    area: 0.0
    models:
      - config/mc_switches.spice
      - sky130A/libs.tech/ngspice/sky130.lib.spice tt
    inputs:
      - IN
    outputs:
      - Q
    clock: "posedge CLK"
    state:
      - "IQ = IN"
    functions:
      - "IQ = IN"
      - "Q = IQ"
    data_slews:
      - 0.02
      - 0.1
      - 0.2
    clock_slews:
      - 0.02
      - 0.1
      - 0.2
    loads:
      - 0.005
      - 0.02
      - 0.05
    setup_time_range:
      - -0.5
      - 0.5
    hold_time_range:
      - -0.5
      - 0.5